package constant

const (
	DEFAULT_SEARCH_VALUE = ""
	DEFAULT_PAGE         = 1
	DEFAULT_LIMIT        = 10

	PHARMACIST_DEFAULT_SEARCH_BY  = "email"
	PHARMACIST_DEFAULT_SORT_BY    = "created_at"
	PHARMACIST_DEFAULT_SORT_ORDER = "desc"

	PHARMACY_DEFAULT_SEARCH_BY = "name"

	PRODUCT_CATEGORY_DEFAULT_SEARCH_BY  = "name"
	PRODUCT_CATEGORY_DEFAULT_SORT_BY    = "name"
	PRODUCT_CATEGORY_DEFAULT_SORT_ORDER = "asc"

	PRODUCT_DEFAULT_SEARCH_BY  = "name"
	PRODUCT_DEFAULT_SORT_BY    = "created_at"
	PRODUCT_DEFAULT_SORT_ORDER = "desc"

	PARTNER_DEFAULT_SEARCH_BY  = "name"
	PARTNER_DEFAULT_SORT_BY    = "id"
	PARTNER_DEFAULT_SORT_ORDER = "asc"

	CATALOG_DEFAULT_SEARCH_BY  = "name"
	CATALOG_DEFAULT_SORT_BY    = "created_at"
	CATALOG_DEFAULT_SORT_ORDER = "desc"

	USER_DEFAULT_SEARCH_BY = "email"

	PENDING_ORDER_DEFAULT_SORT_BY    = "created_at"
	PENDING_ORDER_DEFAULT_SORT_ORDER = "desc"
)
